// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtyNPVX-G_CeHdMblYRCpy3bgss1YAJs4',
    appId: '1:369533890888:web:a93f3afbf28fe1d0f1037d',
    messagingSenderId: '369533890888',
    projectId: 'rayrides-app',
    authDomain: 'rayrides-app.firebaseapp.com',
    storageBucket: 'rayrides-app.firebasestorage.app',
    measurementId: 'G-V28FG3G6P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu5o7Ka5tFdfiUiOkuR5mVJsYGSR1IC_0',
    appId: '1:369533890888:android:43e87fad409f314af1037d',
    messagingSenderId: '369533890888',
    projectId: 'rayrides-app',
    storageBucket: 'rayrides-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6nM9JPNMjhwSuI1iNR5tPKgGa6W6NtFU',
    appId: '1:369533890888:ios:e3053698b43541dcf1037d',
    messagingSenderId: '369533890888',
    projectId: 'rayrides-app',
    storageBucket: 'rayrides-app.firebasestorage.app',
    iosBundleId: 'com.example.rayride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6nM9JPNMjhwSuI1iNR5tPKgGa6W6NtFU',
    appId: '1:369533890888:ios:e3053698b43541dcf1037d',
    messagingSenderId: '369533890888',
    projectId: 'rayrides-app',
    storageBucket: 'rayrides-app.firebasestorage.app',
    iosBundleId: 'com.example.rayride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtyNPVX-G_CeHdMblYRCpy3bgss1YAJs4',
    appId: '1:369533890888:web:ff865276928de976f1037d',
    messagingSenderId: '369533890888',
    projectId: 'rayrides-app',
    authDomain: 'rayrides-app.firebaseapp.com',
    storageBucket: 'rayrides-app.firebasestorage.app',
    measurementId: 'G-73BECRWSCK',
  );
}
